ReadyRecruit/Models/Mainstep.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadyRecruit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Mainstep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mainstep()
        {
            this.Headsteps = new HashSet<Headstep>();
            this.MainStats = new HashSet<MainStat>();
        }
    
        public int MainstepID { get; set; }

        [Required]
        public decimal Number { get; set; }

        [Required]
        public string Name { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> DueDate { get; set; }

        [Required, Display(Name = "Finished?")]
        public bool IsDone { get; set; }

        public string Notes { get; set; }

        [Required]
        public decimal Points { get; set; }

        public int RoadmapID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Headstep> Headsteps { get; set; }
        public virtual Roadmap Roadmap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainStat> MainStats { get; set; }
    }
}

ReadyRecruit/Controllers/MainstepsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReadyRecruit.Models;
using Microsoft.AspNet.Identity;

namespace ReadyRecruit.Controllers
{
    public class MainstepsController : Controller
    {
        private ReadyRecruitEntities db = new ReadyRecruitEntities();

        // GET: Mainsteps
        public ActionResult Index()
        {
            var mainsteps = db.Mainsteps.Include(m => m.Roadmap);
            return View(mainsteps.ToList());
        }

        // GET: Populate Database
        public ActionResult Populate()
        {
            var mainsteps = db.Mainsteps.Include(m => m.Roadmap);

            //populates mainsteps for roadmaps 2 through 5 (1 and 6 already exist
            //Mainstep newitem = new Mainstep();
            //for (int road = 2; road < 6; road++)
            //{
            //    for (int m = 1; m <= 7; m++)
            //    {
            //        newitem.Number = (from ms in db.Mainsteps
            //                          where ms.RoadmapID == 1 &&
            //                          ms.Number == m
            //                          select ms.Number).FirstOrDefault();
            //        newitem.Name = (from ms in db.Mainsteps
            //                        where ms.RoadmapID == 1 &&
            //                        ms.Number == m
            //                        select ms.Name).FirstOrDefault();
            //        newitem.IsDone = false;
            //        newitem.Points = 0;
            //        newitem.RoadmapID = road;
            //        db.Mainsteps.Add(newitem);
            //        db.SaveChanges();
            //    }
            //}

            //must populate roadmaps next
            //Roadmap rditem = new Roadmap();

            //rditem.RoadmapName = "a commissioned officer in the Army";
            //db.Roadmaps.Add(rditem);
            //db.SaveChanges();
            //rditem.RoadmapName = "a commissioned officer in the Air Force";
            //db.Roadmaps.Add(rditem);
            //db.SaveChanges();
            //rditem.RoadmapName = "a commissioned officer in the Navy";
            //db.Roadmaps.Add(rditem);
            //db.SaveChanges();
            //rditem.RoadmapName = "a commissioned officer in the Marines";
            //db.Roadmaps.Add(rditem);
            //db.SaveChanges();
            //rditem.RoadmapName = "a commissioned officer in the Coast Guard";
            //db.Roadmaps.Add(rditem);
            //db.SaveChanges();
            //rditem.RoadmapName = "a warrant officer in the Army";
            //db.Roadmaps.Add(rditem);
            //db.SaveChanges();
            //rditem.RoadmapName = "a warrant officer in the Air Force";
            //db.Roadmaps.Add(rditem);
            //db.SaveChanges();
            //rditem.RoadmapName = "a warrant officer in the Navy";
            //db.Roadmaps.Add(rditem);
            //db.SaveChanges();
            //rditem.RoadmapName = "a warrant officer in the Marines";
            //db.Roadmaps.Add(rditem);
            //db.SaveChanges();
            //rditem.RoadmapName = "a warrant officer in the Coast Guard";
            //db.Roadmaps.Add(rditem);
            //db.SaveChanges();


            //populates mainsteps for roadmaps 7 through 16 (1 through 6 already exist)
            //Mainstep newitem = new Mainstep();
            //for (int road = 7; road < 17; road++)
            //{
            //    for (int m = 1; m <= 7; m++)
            //    {
            //        newitem.Number = (from ms in db.Mainsteps
            //                          where ms.RoadmapID == 1 &&
            //                          ms.Number == m
            //                          select ms.Number).FirstOrDefault();
            //        newitem.Name = (from ms in db.Mainsteps
            //                        where ms.RoadmapID == 1 &&
            //                        ms.Number == m
            //                        select ms.Name).FirstOrDefault();
            //        newitem.IsDone = false;
            //        newitem.Points = 0;
            //        newitem.RoadmapID = road;
            //        db.Mainsteps.Add(newitem);
            //        db.SaveChanges();
            //    }
            //}
            //populates headsteps for roadmaps 2 through 5
            //Headstep newheadstep = new Headstep();
            //for (int road = 2; road < 6; road++)
            //{
            //    //select first 17 headsteps (for roadmap 1, mainsteps 1 through 7)
            //    var headsteps = (from step in db.Headsteps
            //                     where step.MainstepID <= 7
            //                     select step).ToList();
            //    foreach (var h in headsteps)
            //    {
            //        newheadstep.Number = h.Number;
            //        newheadstep.Name = h.Name;
            //        newheadstep.IsDone = false;
            //        newheadstep.Points = 0;
            //        newheadstep.MainstepID = road * 7 + h.MainstepID;
            //        db.Headsteps.Add(newheadstep);
            //        db.SaveChanges();
            //    }
            //}

            //populates headsteps for roadmaps 7 through 16
            //Headstep newheadstep = new Headstep();
            //for (int road = 7; road < 17; road++)
            //{
            //    //select first 17 headsteps (for roadmap 1, mainsteps 1 through 7)
            //    var headsteps = (from step in db.Headsteps
            //                     where step.MainstepID <= 7
            //                     select step).ToList();
            //    foreach (var h in headsteps)
            //    {
            //        newheadstep.Number = h.Number;
            //        newheadstep.Name = h.Name;
            //        newheadstep.IsDone = false;
            //        newheadstep.Points = 0;
            //        newheadstep.MainstepID = (road-1) * 7 + 1 + h.MainstepID;
            //        db.Headsteps.Add(newheadstep);
            //        db.SaveChanges();
            //    }
            //}

            //populates substeps for roadmap 6
            //Substep newsubstep = new Substep();
            //int road = 6;
            ////select first 45 substeps (for roadmap 1, mainsteps 1 through 7, headsteps 1-18)
            //var substeps = (from step in db.Substeps
            //                where step.HeadstepID <= 18
            //                select step).ToList();
            //foreach (var s in substeps)
            //{
            //    newsubstep.Number = s.Number;
            //    newsubstep.Name = s.Name;
            //    newsubstep.IsDone = false;
            //    newsubstep.Points = 0;
            //    newsubstep.HeadstepID = GetID(road, s);
            //    db.Substeps.Add(newsubstep);
            //    db.SaveChanges();
            //}

            //populates substeps for roadmap 2 through 5
            //Substep newsubstep = new Substep();
            //for (int road = 2; road < 6; road++)
            //{
            //    //select first 45 substeps (for roadmap 1, mainsteps 1 through 7, headsteps 1-18)
            //    var substeps = (from step in db.Substeps
            //                    where step.HeadstepID <= 18
            //                    select step).ToList();
            //    foreach (var s in substeps)
            //    {
            //        newsubstep.Number = s.Number;
            //        newsubstep.Name = s.Name;
            //        newsubstep.IsDone = false;
            //        newsubstep.Points = 0;
            //        newsubstep.HeadstepID = GetID(road, s);
            //        db.Substeps.Add(newsubstep);
            //        db.SaveChanges();
            //    }
            //}

            //populates substeps for roadmap 7 through 16
            //Substep newsubstep = new Substep();
            //for (int road = 7; road < 17; road++)
            //{
            //    //select first 45 substeps (for roadmap 1, mainsteps 1 through 7, headsteps 1-18)
            //    var substeps = (from step in db.Substeps
            //                    where step.HeadstepID <= 18
            //                    select step).ToList();
            //    foreach (var s in substeps)
            //    {
            //        newsubstep.Number = s.Number;
            //        newsubstep.Name = s.Name;
            //        newsubstep.IsDone = false;
            //        newsubstep.Points = 2;
            //        newsubstep.HeadstepID = GetID(road, s);
            //        db.Substeps.Add(newsubstep);
            //        db.SaveChanges();
            //    }
            //}

            //set points to 2 for substeps 46 to 260
            //    var substeps = (from step in db.Substeps
            //                    where step.SubstepID >= 46 &&
            //                    step.SubstepID <= 260
            //                    select step).ToList();
            //    foreach (var s in substeps)
            //    {
            //        s.Points = 2;
            //        db.SaveChanges();
            //    }
            //    return RedirectToAction("StepPage");
            //}

            //delete unused headings (must delete their stat tables first) --isn't working
            //var headsteps = (from step in db.Headsteps
            //                 where step.Name == "???"
            //                 select step);
            //var headstep = headsteps.FirstOrDefault();

            //foreach (var h in headsteps)
            //{
            //    var headstats = (from stat in db.HeadStats
            //                     where stat.HeadstepID == h.HeadstepID
            //                     select stat);
            //    var headstat = headstats.FirstOrDefault();
            //    foreach (var s in headstats)

ReadyRecruit/Views/Mainsteps/Create.cshtml
@model ReadyRecruit.Models.Mainstep

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Mainstep</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDone)
                    @Html.ValidationMessageFor(model => model.IsDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Points, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Points, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Points, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoadmapID, "RoadmapID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoadmapID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoadmapID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReadyRecruit/Views/Mainsteps/Delete.cshtml
@model ReadyRecruit.Models.Mainstep

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Mainstep</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Points)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Points)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Roadmap.RoadmapName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Roadmap.RoadmapName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ReadyRecruit/Views/Mainsteps/Details.cshtml
@model ReadyRecruit.Models.Mainstep

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Mainstep</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Points)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Points)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Roadmap.RoadmapName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Roadmap.RoadmapName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MainstepID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ReadyRecruit/Views/Mainsteps/Edit.cshtml
@model ReadyRecruit.Models.Mainstep

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Mainstep</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MainstepID)

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDone)
                    @Html.ValidationMessageFor(model => model.IsDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Points, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Points, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Points, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoadmapID, "RoadmapID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoadmapID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoadmapID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReadyRecruit/Views/Mainsteps/Index.cshtml
@model IEnumerable<ReadyRecruit.Models.Mainstep>

@{
    ViewBag.Title = "Mainstep";
}

<h2>Mainsteps</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MainstepID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Points)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Roadmap.RoadmapID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Roadmap.RoadmapName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MainstepID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Points)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Roadmap.RoadmapID)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Roadmap.RoadmapName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MainstepID }) |
            @Html.ActionLink("Details", "Details", new { id=item.MainstepID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MainstepID })
        </td>
    </tr>
}

</table>

ReadyRecruit/Views/Mainsteps/Navbar.cshtml
<div class="navbar navbar-static-top" id="navvy">
    <div class="container-fluid">
        <div class="navbar-header">
            <a id="Home" class="navbar-brand" href="~/Home/Index"><span><img src="~/Content/images/Ready Recruit!_clipped_rev_1.png" /></span></a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="glyphicon glyphicon-glass"></span>
            </button>
            @*@Html.ActionLink("Ready Recruit", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

ReadyRecruit/Views/Mainsteps/NewRoadmap.cshtml
@model IEnumerable<ReadyRecruit.Models.Pages>
@using ReadyRecruit.Models

@{
    ViewBag.Title = "NewRoadmap";
}



<div class="specialVideo">
@if (ViewBag.Rdmap == 1)
{
    <h1 class="container" id="trailer"><iframe width="560" height="315" src="https://www.youtube.com/embed/jD-PdA4-W9A" frameborder="0" allowfullscreen></iframe>
    Welcome to the Army!</h1>
    <button type="button" class="btn btn-default">
        @Html.ActionLink("Continue", "StepPage", "Mainsteps", protocol: null, hostName: null, fragment: "Step4", routeValues: null, htmlAttributes: null)
    </button>

}
else if (ViewBag.Rdmap == 2)
{ 
    <h2>Welcome to the Air Force!</h2>
    <h1 class="container" id="trailer"><iframe width="1000" height="600" src="https://www.youtube.com/watch?v=y3XMUBU6HLc" frameborder="0" allowfullscreen></iframe>
    Welcome to the Air Force!</h1>
    <button type="button" class="btn btn-default">
        @Html.ActionLink("Continue", "StepPage", "Mainsteps", protocol: null, hostName: null, fragment: "Step4", routeValues: null, htmlAttributes: null)
    </button>

}
else if (ViewBag.Rdmap == 3)
{
    <h1 class="container" id="trailer"><iframe width="560" height="315" src="https://www.youtube.com/embed/jD-PdA4-W9A" frameborder="0" allowfullscreen></iframe>
    Welcome to the Navy!</h1>
    <button type="button" class="btn btn-default">
        @Html.ActionLink("Continue", "StepPage", "Mainsteps", protocol: null, hostName: null, fragment: "Step4", routeValues: null, htmlAttributes: null)
    </button>

}
else if (ViewBag.Rdmap == 4)
{
    <h1 class="container" id="trailer"><iframe width="560" height="315" src="https://www.youtube.com/embed/jD-PdA4-W9A" frameborder="0" allowfullscreen>
        Welcome to the Marines</iframe></h1>        
        <button type="button" class="btn btn-default">
            @Html.ActionLink("Continue", "StepPage", "Mainsteps", protocol: null, hostName: null, fragment: "Step4", routeValues: null, htmlAttributes: null)
        </button>

}
else if (ViewBag.Rdmap == 5)
{
    <h1 class="container" id="trailer"><iframe width="560" height="315" src="https://www.youtube.com/embed/jD-PdA4-W9A" frameborder="0" allowfullscreen>
        Welcome to the Coast Guard</iframe></h1>
        <button type="button" class="btn btn-default">
            @Html.ActionLink("Continue", "StepPage", "Mainsteps", protocol: null, hostName: null, fragment: "Step4", routeValues: null, htmlAttributes: null)
        </button>
}
else
{
    <h1 class="container" id="trailer"><iframe width="560" height="315" src="https://www.youtube.com/embed/jD-PdA4-W9A" frameborder="0" allowfullscreen></iframe></h1>
    <button type="button" class="btn btn-default">
        @Html.ActionLink("Continue", "StepPage", "Mainsteps", protocol: null, hostName: null, fragment: "Step4", routeValues: null, htmlAttributes: null)
    </button>

}
</div>